# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

target 'OTPStackViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OTPStackViewExample
  pod 'OTPStackView', :git => 'https://github.com/intan1907/OTPStackView.git', :tag => '1.0.2'
  pod 'IQKeyboardManager'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.2'
    end
  end
end